trigger: none
pr:
  branches:
    include:
    - master

# pool: 
#   vmImage: 'ubuntu-latest'
pool: Default

container: mcr.microsoft.com/mlops/python:latest  


variables:
- group: devopsforai-aml-vg


steps:
- template: azdo-base-pipeline.yml